# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
      - release/*

variables:
  ReleaseTagPrefix: release/

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: echo 'New release created'
    displayName: "Run a one-line script"

  - task: Bash@3
    displayName: Get Version from Release Tag
    inputs:
      filePath: "get-version.sh"
      arguments: $(ReleaseTagPrefix)

  - task: DotNetCoreCLI@2
    displayName: Pack NuGet Package
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/$(ReleaseTagPrefix)'))
    inputs:
      command: "pack"
      packagesToPack: "**/*.csproj"
      versioningScheme: "byPrereleaseNumber"
      majorVersion: $(MajorVersion)
      minorVersion: $(MinorVersion)
      patchVersion: $(PatchVersion)
